name: Sample Pipeline_1676501527572
stages:
  - name: build
    spec:
      steps:
        - name: Send a Slack message
          spec:
            with:
              webhook_url: slackurl
              api_token: slacktoken
              text: hello
              color: "#ffffff"
            uses: slack@3.5.0
          type: bitrise
        - name: go_build
          spec:
            run: go build
          type: script
        - name: go_test
          spec:
            run: go test -v ./...
          type: script
    type: ci
version: 1
