name: Sample Pipeline_1676501527572
stages:
  - name: build
    spec:
      steps:
        - name: Slack
          spec:
            with:
              webhook: https://hooks.slack.com/services/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
              template: test
            uses: ""
          type: plugin
        - name: go_build
          spec:
            run: go build
          type: script
        - name: go_test
          spec:
            run: go test -v ./...
          type: script
    type: ci
version: 1
